- hosts: localhost
  vars_files:
  
  tasks:
  - name: confguring repo for K8s
    yum_repository:
            name: K8s-repo
            description: repo for K8s
            baseurl: "https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64"
            gpgcheck: no
  - name: installing docker
    command: yum install docker-ce --nobest
  - name: starting the docker service
    service: 
        name: docker
        state: started
  - name: installing kubeadm
    package:
         name: kubeadm
         state: present
  - name: starting the kubelet service
    service: 
         name: kubelet
         state: started
  - name: pulling all the docker images
    command: kubeadm config images pull
  - name: setup the driver to systemd 
    copy:
         dest: "/etc/docker/daemon.json"
         content: '{
                   "exec-opts": ["native.cgroupdriver=systemd"]
                   }'
  - name: restarting docker service
    service:
         name: docker
         state: restarted
  - name: installing iproute-tc software
    package:  
         name: iproute-tc
         state: present
  - name: network configuration
    copy: 
        dest: "/etc/sysctl.d/k8s.conf"
        src: "network.conf"
  - name: to start sysctl service
    command: sudo sysctl --system
  - name: Ignoring RAM and CPU errors(system requirements)
    shell: kubeadm init --pod-network-cidr=10.240.0.0/16 --ignore-preflight-errors=NumCPU --ignore-preflight-errors=Mem --ignore-preflight-errors=Swap
  - name: configuring system as client
    shell: "mkdir -p $HOME/.kube; sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config; sudo chown $(id -u):$(id -g) $HOME/.kube/config" 

